#146683081 Front end unit testing setup
andela/haku-cfh pull request #13
Opened 2017-06-12 12:33 UTC by Hector101

#### What does this PR do?
* This PR sets up a front end testing frameworks to the project using Jasmine and Karma

#### Description of Task to be completed?
* Task to be completed installs the required dependencies including - jasmine, jasmine-core, 
karma, karma-chrome-launcher, karmer-cli, and karma-jasmine.
* initialize karma to the project using the command "./node_modules/.bin/karma init" to choose and setup the preferred testing framework, in this case Jasmine and setup the platform to run test, in this case Chrome Browser.

#### How should this be manually tested?
* Run the command  "./node_modules/.bin/karma start" to run test on Chrome browser
* Run test with jasmine using the command "./node_modules/.bin/jasmine"

#### Any background context you want to provide?
* N/A
#### What are the relevant pivotal tracker stories?
* 146683081 Setup unit testing for the front end
#### Screenshots (if appropriate)
* Testing mock file with jasmine
<img width="671" alt="screen shot 2017-06-12 at 1 06 29 pm" src="https://user-images.githubusercontent.com/10426118/27033888-346e282a-4f73-11e7-9731-3736ca15148d.png">

* Mock test file 
<img width="393" alt="screen shot 2017-06-12 at 1 06 47 pm" src="https://user-images.githubusercontent.com/10426118/27033944-6c6b3f88-4f73-11e7-9416-fa8ccf3b2d5f.png">

* Chrome browser testing that karma is working properly
<img width="1049" alt="screen shot 2017-06-12 at 1 16 09 pm" src="https://user-images.githubusercontent.com/10426118/27033978-8e653fd0-4f73-11e7-9d86-af0a871cbf61.png">

#### Questions:
*N/A

2017-06-12 15:32 UTC, tonerdo requested changes
A few comments but I think we're good. You should probably listen to hound-ci as well

2017-06-12 15:32 UTC, tsolarin commented on .env
> +GITHUB_CLIENT_SECRET=
Env keys without values are not ideal. It's either they have a dummy value or they aren't there at all

2017-06-12 15:32 UTC, tsolarin commented on .eslintrc.js
> +      "rules": { "one-var": 0,
Poor formatting. `"one-var": 0` should be on a new line

2017-06-12 15:32 UTC, tonerdo requested changes
A few comments but I think we're good. You should probably listen to hound-ci as well

2017-06-13 10:23 UTC, temilaj commented
Testing bot integration. Ignore this PR

2017-06-13 14:06 UTC, closed without merging