#146683083 Convert from Grunt to Gulp taskrunner
andela/haku-cfh pull request #14
Opened 2017-06-13 13:03 UTC by Tawakalt

#### What does this PR do?
- It converts from Grunt to Gulp taskrunner

#### Description of Task to be completed?

Create gulpfile.js and install dependencies
Delete gruntfile.js and remove dependencies 
Ignore bower_components
Modify scripts to use gulp in package.json.

#### How should this be manually tested?
Running npm start and npm test OR gulp and gulp test

#### Any background context you want to provide?
NONE

#### What are the relevant pivotal tracker stories?
NONE

#### Screenshots (if appropriate)

<img width="990" alt="screen shot 2017-06-13 at 1 46 36 pm" src="https://user-images.githubusercontent.com/23738768/27083237-c487c124-503f-11e7-8c81-321402ebc231.png">
<img width="674" alt="screen shot 2017-06-13 at 1 48 46 pm" src="https://user-images.githubusercontent.com/23738768/27083255-d6ced674-503f-11e7-8b39-96682d6181ea.png">
<img width="831" alt="screen shot 2017-06-13 at 1 49 49 pm" src="https://user-images.githubusercontent.com/23738768/27083285-f1c2c58a-503f-11e7-9b3f-600f2180a4db.png">
<img width="946" alt="screen shot 2017-06-13 at 1 53 02 pm" src="https://user-images.githubusercontent.com/23738768/27083308-0c59e55e-5040-11e7-8d2c-24f5e737f0a3.png">
<img width="929" alt="screen shot 2017-06-13 at 1 53 18 pm" src="https://user-images.githubusercontent.com/23738768/27083396-4f62e2a6-5040-11e7-8bfe-2c81087d1c42.png">

#### Questions:
NONE

2017-06-13 13:46 UTC, tonerdo requested changes
A quick one and we should be good

2017-06-13 13:46 UTC, tsolarin commented on gulpfile.js
> +  gulp.watch('app/**/*js', browserSync.reload());
Shouldn't this be `app/**/*.js`?

2017-06-13 13:50 UTC, tonerdo requested changes
A quick one and we should be good

2017-06-15 11:16 UTC, Tawakalt commented on gulpfile.js
> +  gulp.watch('app/**/*js', browserSync.reload());
Yes. Fixed it

2017-06-19 08:53 UTC, tsolarin commented
@Tawakalt kindly fix the merge conflicts and we'll be good

2017-06-21 09:24 UTC, tonerdo approved these changes

2017-06-21 09:25 UTC, merged