Chore/146687435/stabilise base application
andela/haku-cfh pull request #19
Opened 2017-06-21 11:06 UTC by joel-ace

###What does this PR do?
fix dependency issues so app can be deployed on heroku without errors
fix merge conflicts

###Description of Task to be completed?
None

###How should this be manually tested?
None

###Any background context you want to provide?
None

###What are the relevant pivotal tracker stories?
None

###Screenshots (if appropriate)
None

###Questions:
None

2017-06-21 11:18 UTC, tonerdo requested changes
A bunch of things you need to look at. Also your PR description isn't well formatted

2017-06-21 11:18 UTC, tonerdo commented on .env
> +MONGOHQ_URL=mongodb://cfh:qwerty1234@ds123752.mlab.com:23752/haku-cfh
DO NOT put service credentials in a public repo

2017-06-21 11:18 UTC, tonerdo commented on .env
>  TWITTER_CONSUMER_KEY=
It's either you give env keys values or don't put them at all

2017-06-21 11:18 UTC, tonerdo commented on .gitignore
> +>>>>>>> 7278826f71864b65073709d7ff0e018f5d94dd59
Why was a merge conflict marker commited?

2017-06-21 11:18 UTC, tonerdo commented on config/env/all.js
> +    db: process.env.MONGOLAB_URL
You env file says `MONGOHQ_URL` but this says MONGOLAB_URL

2017-06-21 11:18 UTC, tonerdo commented on sample.env
> +GITHUB_CLIENT_SECRET=
It's either you give env keys values or don't put them at all. What exactly does this file do?

2017-06-21 18:10 UTC, joel-ace commented on sample.env
> +GITHUB_CLIENT_SECRET=
The file contains environment variables associated with this project. This is to ensure all team members sync while working on different projects

2017-06-22 09:40 UTC, tonerdo requested changes

2017-06-22 09:40 UTC, tonerdo commented on config/env/all.js
> +    db: process.env.MONGOLAB_URL
You need a default value for `db` much like you have for `port`

2017-06-27 17:38 UTC, tonerdo requested changes

2017-06-27 17:38 UTC, tonerdo commented on config/env/all.js
> +    db: process.env.MONGOLAB_URL || 'localhost',
This is very wrong and will not work. Where's the `mongodb://` prefix before `localhost`? Kindly look up how to construct a valid mongodb connection url

2017-06-27 18:02 UTC, tonerdo approved these changes

2017-06-27 18:03 UTC, merged