Feature/146683087/get jwt on login
andela/haku-cfh pull request #21
Opened 2017-06-30 16:00 UTC by codejockie

Pull Request Convention

#146683087 Users should receive a JWT on successful login
#146683089 Users should receive a JWT on successful signup

    #### What does this PR do?
    #### This PR changes the authentication method from session auth to JWT auth

    #### Description of Tasks to be completed
    #### Users once authenticated via the login api should be returned a JWT to be required on subsequent call to all other endpoints that require authentication
    #### Users once authenticated via the signup api should be returned a JWT to be required on subsequent call to all other endpoints that require authentication

    #### How should this be manually tested?
    #### N/A

    #### Any background context you want to provide?
    #### No

    #### What are the relevant pivotal tracker stories?
    #### Users should receive a JWT on successful login
    #### Users should receive a JWT on successful signup

    #### Screenshots (if appropriate)
    #### None

    #### Questions:
    #### None

2017-07-03 15:16 UTC, tonerdo approved these changes

2017-07-05 10:53 UTC, tonerdo requested changes

2017-07-05 10:53 UTC, tonerdo commented on public/js/directives.js
> +        // }
Don't commit commented out code

2017-07-05 10:53 UTC, tonerdo commented on server.js
> +require('dotenv').config();
Why? You're not using an `.env` file

2017-07-05 10:55 UTC, codejockie commented on server.js
> +require('dotenv').config();
I didn't add that require statement, it was part of the original codebase. for the commented code, I'd fix that.

2017-07-05 10:56 UTC, codejockie commented on public/js/directives.js
> +        // }
should I close the PR?

2017-07-05 10:58 UTC, tonerdo commented on public/js/directives.js
> +        // }
@codejockie please don't ask me this question. I've talked with you guys about this before

2017-07-05 10:59 UTC, codejockie commented on public/js/directives.js
> +        // }
I know what to do. Thank you.

2017-07-05 11:03 UTC, codejockie commented on server.js
> +require('dotenv').config();
Done.

2017-07-07 13:33 UTC, tonerdo approved these changes

2017-07-07 13:36 UTC, closed without merging